export const RECENTLY_VIEWED_CARD_WIDTH = 120;
export const RECENTLY_VIEWED_COVER_ASPECT_RATIO = 2 / 3;

export const TRACKING_COVER_ASPECT_RATIO = RECENTLY_VIEWED_COVER_ASPECT_RATIO;
export const TRACKING_COVER_HEIGHT = 96;
export const TRACKING_COVER_WIDTH = Math.round(TRACKING_COVER_HEIGHT * TRACKING_COVER_ASPECT_RATIO);
